### ISSUE TITLE
 Fixed text FileSystemWatcherTest.bootstrapAndUpdatenet on windows

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#113]
could you have a look at this test that only fails on Window, thanks

https://teamcity.chronicle.software/buildConfiguration/OpenHFT_ChronicleCore_SnapshotWindows/407466?mode=builds

**Comment by minborg** [comment]
It fails locally on my Mac too.

**Comment by jatindersangha** [comment]
Hi Rob,

 

I’ll have a look at it today.

 

Thanks,

--Jatinder

**Comment by RobAustin** [comment]
@jatindersangha any news on this issue?

**Comment by jatindersangha** [comment]
The issue appears to be that the NIO file-watching service is very platform dependent.

Eg. Linux does not produce events when a directory-entry is updated, WIndows does.
Eg. Windows does not produce events when a file is opened for write - Linux does.

This makes the results of this particular test heavily dependent on the platform.

A practical solution would be to modify the test and framework so that only major events are generated (file created, modified etc) and filter out the unhelpful events (if possible ;-)

In the meantime, this test has been ignored for Windows.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
