### ISSUE TITLE
retryReadVolatileInt() spamming stdout

### ISSUE THREAD

**Issue by mcs6502** [OpenHFT/Chronicle-Core#19]
The System.out.println() call in [UnsafeMemory.retryReadVolatileInt()](https://github.com/OpenHFT/Chronicle-Core/commit/d6c7f0a19aa743bb943b87114d2c8c1f4c52119f) produces an excessive amount of output on the console. This behaviour occurs when multiple appenders within the same process simultaneously write to the same Chronicle Queue file. (Each appender has its own instance of SingleChronicleQueue.)
Please could you remove or replace this System.out.println() call, and clarify how to avoid the situations where this condition is triggered.
Please could you also prepare a Chronicle Queue release that utilises the updated version of Chronicle Core that contains this correction.

**Comment by peter-lawrey** [comment]
You need to add padding to avoid cache misaligned CAS operations. Engine
does this automatically. We could add an option to queue to do the same.
This is reporting an observed limitation of the CPU so we can't ignore it.

**Comment by mcs6502** [comment]
I have added "appender.padToCacheAlign(MarshallableOut.Padding.ALWAYS)" on each appender right after acquiring it, and the problem still persists (getting lots of System.out spam).
Please could you use a logger in place of System.out for logging the warning messages, or suggest an alternative workaround for misaligned cache access in chronicle-core?

**Comment by peter-lawrey** [comment]
In that case there is something wrong which definitely shouldn't be
ignored. Can you send us a sample of the logs as padding should prevent
this from occurring, or at least it has in all the cases we are aware of.
What this message is complaining about is that the CAS operation is not
acting atomically which is a basic assumption about the use of this
primitive.

On 3 Nov 2016 00:31, "mcs6502" <notifications@github.com> wrote:

I have added "appender.padToCacheAlign(MarshallableOut.Padding.ALWAYS)" on
each appender right after acquiring it, and the problem still persists
(getting lots of System.out spam).
Please could you use a logger in place of System.out for logging the
warning messages, or suggest an alternative workaround for misaligned cache
access in chronicle-core?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/OpenHFT/Chronicle-Core/issues/19#issuecomment-258040009>,
or mute the thread

**Comment by mcs6502** [comment]
I've attached a snippet of stdout with these messages. Apparently they are unrelated to CAS but rather to the clearing of the "incomplete" flag, which is expected behaviour.
{quote}
    public long readVolatileLong(long address) {
        long value = UNSAFE.getLongVolatile(null, address);
        if ((address & 63) <= 54) {
            return value;
        }
        return retryReadVolatileInt(address, value);
    }
{quote}
[was_is_now.txt](https://github.com/OpenHFT/Chronicle-Core/files/570803/was_is_now.txt)

**Comment by peter-lawrey** [comment]
This is the way we detect that there was a problem with the CAS which is
performing the write operation this is attempting to read.

238c100*7f* *(63)* was 80000058 is now 58
1fcc116*fe* (*62*) was 80000058 is now 58
1a2c756*bd* (*61*) was 80000058 is now 58

The number between () is the offset within a cache line. (61), (62) or (63)
means that a volatile read of a value which crosses cache lines is being
read and the code has detected that this CAS wasn't written safely. i.e.
80000058 is a value we never write so to see it means the CAS write was not
atomic.  This can only happen when padding is not used.

In a the next version be are planning to remove the option to avoid
padding. But for now, if you have concurrent writers, you have to enable
padding which is added to the end of entries close to the end of a cache
line.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
