### ISSUE TITLE
Public API utility methods should not be enums

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#196]
We should use nonintantiable classes instead as enums exposes unwanted methods in the API.

**Comment by peter-lawrey** [comment]
We should make it explicit how many instances of utility classes we should expect to see which is 0 rather than making it indirectly with a private constructor which can be called from a nested class or reflection for example. There are many examples in our code and others where you get a constructor and call setAccessible(true) and this allows utility instances to be created via deserialization i.e. input. This doesn't apply to `enum`s.

NOTE: we do create new instances of "dynamic" `enum` but this doesn't use reflection and has checks on it. i.e. the class must extend `DynamicEnum` only Unsfae.allocateInstance can create new instances of a enum so is less likely to used/misused.

**Comment by minborg** [comment]
As described in one of my older blog posts (http://minborgsjavapot.blogspot.com/2015/01/enforcing-java-singletons-is-very-hard.html) it is actually possible to create spurious enum constants as well. So, I think the capability to create unwanted instances is there for both alternatives: Enum or utility class. However, I think this is of less importance. If a user wants to create an instance of a class that is not supposed to be created, then let them go ahead.

My argument for using utility classes (i.e. non-instantiable final classes with a private constructor) over Enums is purely based on API management. Adding a public Enum class will have the following adverse effects on the API:

A) It adds `extends Enum` to the class
A1) It adds `implements Serializable` to the class
A2) It adds a `implements Comparable` to the class
B) It adds a static `valueOf(tring)` method
C) It adds a static `valueOf(Class, String)` method
D) It adds a static `values()` method

Other issues:
Some users are confused when there is an Enum with zero elements.
Code completion in the IDE will be polluted with the non-related enum methods (B, C and D)
It adds some extra enum properties to the class definition

So, if we have N classes of Enum utility classes, then we will add an additional of N*3 methods to maintain when ensuring version compatibility. Also, there will be N different static methods doing the same thing (e.g. `Foo.valueOf(Class, String)`, `Bar.valueOf(Class, String)` etc)

A more stringent way of enforcing a no-instance-property would be to create utility classes like this:

```
public final class FooUtil {

    private FooUtil() {
        throw new UnsupportedOperationException();
    }

    public static int bar() {
        return 42;
    }

}

```
This has the advantage of not providing any unrelated API methods and (almost) guarantees that no instances are created. (Well,  there is always instrumentation, isn't it?)

I think utility classes in internal packages (not exposed in the public API) may or may not be Enums.
