### ISSUE TITLE
Move AbstractCloseable#throwExceptionIfClosed to an expert use interface

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#220]
throwExceptionIfClosed is a public method, as such, it should probably be moved into its own class, or not made public, as being public is leaking its visibility into the subclasses API. The current method is also mixing concerns because it's also doing both thread checks as well as checking if closed. When the thread check is not required currently the way to turn this off is to override the functionality ( which is a little ugly )

**Comment by RobAustin** [comment]
@minborg what do you you think, what changes do you think we should make here

**Comment by minborg** [comment]
I would suggest something along these lines:

https://github.com/OpenHFT/Chronicle-Core/tree/feature/closeable/src/main/java/net/openhft/chronicle/core/resource

The `FooResource` is using a `ManagedResourceSupport` class to handle resource management. This means it is using something rather than being something. This provides better API control and also opens up for specialized support implementations that can be optimized (e.g. if no thread confinement is needed, a more optimized class can be supplied by the builder). 

There are many aspects to this and I am just showing a rough outline here.

I think these ideas could be realized in a new future core major version bump. In the short term, I would consider splitting up close and thread assertions into separate methods. I would name the thread checking method `assertThreadConfined()`.

**Comment by peter-lawrey** [comment]
Marked three methods to be moved to `ManagedCloseable` in `x.22`
and changed our code to use `ManagedCloseable` now.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.21ea45](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.21ea45), [BOM-2.21ea114](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea114)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.21ea48](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.21ea48), [BOM-2.21ea134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea134)
