### ISSUE TITLE
Extract JLBH into its own project

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Core#91]
@peter-lawrey @RobAustin 
Wishes from Joker ;D

**Comment by RobAustin** [comment]
Do you know of someone that would be willing to do the migration if we granted them access ?

**Comment by dpisklov** [comment]
I know myself... It takes like 5 min I reckon

**Comment by RobAustin** [comment]
Ok then create a new repo and move it. Although I don’t understand why they can’t use It in the current repo. What’s the benefit of moving it out of core. 

There is of course the added job of changing the place(s) where it is used for example in the fix benchmarks and changing the release job so that it builds when the BOM is updated.  But if it’s that’s simple and you you can do all this in 5 mins, probably better to spend the time in moving it rather than us all debating why we should or should not move it, also can you move our documentation we have if it ( if any ) into this new repo as well 

Thanks

**Comment by dpisklov** [comment]
New home: https://github.com/OpenHFT/JLBH

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.17.29](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.17.29), [BOM-2.17.434](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.434)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
